import unittest
from pathlib import Path
from tempfile import NamedTemporaryFile
from types import SimpleNamespace

from app.ai_extractor import (
    AIClassification,
    AIExtractionUnavailable,
    AIExtractionBatch,
    OpenAIExtractor,
    apply_ai_review,
)
from app.normalizer import normalize_estimate_text


class FakeExtractor:
    def __init__(self, classifications):
        self.classifications = classifications
        self.calls = []

    def classify(self, estimate_text, categories):
        self.calls.append({"text": estimate_text, "categories": categories})
        return AIExtractionBatch(classifications=self.classifications)


class UnavailableExtractor:
    def classify(self, estimate_text, categories):
        raise AIExtractionUnavailable("No credits")


class AIExtractorTests(unittest.TestCase):
    def setUp(self):
        self.text = (
            "Example Painting Co.\n"
            "Leave the premises broom clean at completion.\n"
            "All waste generated by our crew will be taken off site.\n"
            "ESTIMATE TOTAL $2,000.00"
        )

    def test_accepts_supported_classification_with_exact_evidence(self):
        estimate = normalize_estimate_text(self.text)
        extractor = FakeExtractor(
            [
                AIClassification(
                    category="cleanup",
                    status="included",
                    evidence="Leave the premises broom clean at completion.",
                    confidence=0.94,
                )
            ]
        )

        result = apply_ai_review(self.text, estimate, extractor)

        self.assertEqual(result["cleanup"]["status"], "included")
        self.assertEqual(result["cleanup"]["source"], "ai")
        self.assertEqual(result["cleanup"]["confidence"], 0.94)
        self.assertFalse(result["cleanup"]["review_required"])
        self.assertIn("cleanup", extractor.calls[0]["categories"])

    def test_rejects_evidence_not_found_in_document(self):
        estimate = normalize_estimate_text(self.text)
        extractor = FakeExtractor(
            [
                AIClassification(
                    category="cleanup",
                    status="included",
                    evidence="Full cleanup and sanitation are included.",
                    confidence=0.99,
                )
            ]
        )

        result = apply_ai_review(self.text, estimate, extractor)

        self.assertEqual(result["cleanup"]["source"], "rule")
        self.assertTrue(result["cleanup"]["review_required"])

    def test_accepts_not_stated_without_evidence(self):
        estimate = normalize_estimate_text(self.text)
        extractor = FakeExtractor(
            [
                AIClassification(
                    category="labor_warranty",
                    status="not_stated",
                    evidence=None,
                    confidence=0.91,
                )
            ]
        )

        result = apply_ai_review(self.text, estimate, extractor)

        self.assertEqual(result["labor_warranty"]["source"], "ai")
        self.assertFalse(result["labor_warranty"]["review_required"])

    def test_skips_model_when_no_categories_need_review(self):
        text = (
            "Walls include two finish coats. Cleanup is included. "
            "Debris disposal is included. One-year labor warranty included. "
            "Primer is included. Ceilings are included. Minor drywall repair included."
        )
        estimate = normalize_estimate_text(text)
        extractor = FakeExtractor([])

        result = apply_ai_review(text, estimate, extractor)

        self.assertIs(result, estimate)
        self.assertEqual(extractor.calls, [])

    def test_normalizer_preserves_rules_when_ai_is_unavailable(self):
        result = normalize_estimate_text(self.text, UnavailableExtractor())

        self.assertEqual(result["cleanup"]["source"], "rule")
        self.assertTrue(result["cleanup"]["review_required"])

    def test_transcribes_pdf_and_deletes_remote_file(self):
        class FakeFiles:
            def __init__(self):
                self.deleted = []

            def create(self, **kwargs):
                self.purpose = kwargs["purpose"]
                return SimpleNamespace(id="file-test")

            def delete(self, file_id):
                self.deleted.append(file_id)

        class FakeResponses:
            def create(self, **kwargs):
                self.request = kwargs
                return SimpleNamespace(output_text="ACME QUOTE\nTOTAL $900.00")

        client = SimpleNamespace(files=FakeFiles(), responses=FakeResponses())
        extractor = OpenAIExtractor(client=client, model="test-model")
        with NamedTemporaryFile(suffix=".pdf") as temporary_pdf:
            temporary_pdf.write(b"%PDF-test")
            temporary_pdf.flush()
            result = extractor.transcribe_pdf(Path(temporary_pdf.name))

        self.assertEqual(result, "ACME QUOTE\nTOTAL $900.00")
        self.assertEqual(client.files.purpose, "user_data")
        self.assertEqual(client.files.deleted, ["file-test"])
        content = client.responses.request["input"][0]["content"]
        self.assertEqual(content[0]["file_id"], "file-test")


if __name__ == "__main__":
    unittest.main()
