from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


OUTPUT_PATH = Path(
    "sample-data/quotes/synthetic-painting-estimate-summit-semantic.pdf"
)


def build_estimate() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    document = SimpleDocTemplate(
        str(OUTPUT_PATH),
        pagesize=LETTER,
        leftMargin=0.62 * inch,
        rightMargin=0.62 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
        title="Summit Surface Renewal Estimate",
        author="Summit Surface Renewal",
    )

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=27,
        textColor=colors.HexColor("#24334a"),
        spaceAfter=5,
    )
    heading = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#24334a"),
        spaceBefore=10,
        spaceAfter=6,
    )
    body = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=9.4,
        leading=14,
        textColor=colors.HexColor("#344256"),
    )
    small = ParagraphStyle(
        "Small",
        parent=body,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#667085"),
    )
    right = ParagraphStyle("Right", parent=body, alignment=TA_RIGHT)

    story = [
        Paragraph("SUMMIT SURFACE RENEWAL", title),
        Paragraph("Residential turnover proposal | Riverside County", small),
        Spacer(1, 15),
    ]

    summary = Table(
        [
            ["Estimate", "SSR-2217", "Issued", "August 31, 2026"],
            ["Prepared for", "Cedar Lane Apartments", "Property", "980 University Ave, Riverside, CA"],
        ],
        colWidths=[0.8 * inch, 1.7 * inch, 0.65 * inch, 3.5 * inch],
    )
    summary.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f3f7")),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#c7cfda")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d9dfe7")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#344256")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.extend([summary, Spacer(1, 17), Paragraph("PROPOSED WORK", heading)])

    descriptions = [
        (
            "Preparation and finish",
            "Correct everyday fastener impressions and shallow surface blemishes. "
            "Seal repaired areas before finish application. Refresh interior wall "
            "surfaces with two complete applications of washable eggshell coating.",
            "$2,640.00",
        ),
        (
            "Upper surfaces",
            "Overhead surfaces throughout the living room, hall, bedrooms, kitchen, "
            "and bathroom will receive one uniform application of flat white coating.",
            "$780.00",
        ),
        (
            "Woodwork",
            "Renew baseboards, door frames, and six interior doors with one application "
            "of durable satin enamel.",
            "$920.00",
        ),
        (
            "Project completion",
            "The crew will leave the premises broom clean at completion. All waste "
            "generated by our crew will be taken off site.",
            "$310.00",
        ),
    ]
    rows = [["SERVICE", "DETAIL", "AMOUNT"]]
    rows.extend(
        [Paragraph(name, body), Paragraph(description, body), Paragraph(amount, right)]
        for name, description, amount in descriptions
    )
    work = Table(rows, colWidths=[1.3 * inch, 4.4 * inch, 0.85 * inch], repeatRows=1)
    work.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#24334a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d9dfe7")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend([work, Spacer(1, 13)])

    totals = Table(
        [
            [Paragraph("Project price", body), Paragraph("$4,650.00", right)],
            [Paragraph("ESTIMATE TOTAL", heading), Paragraph("$4,650.00", right)],
        ],
        colWidths=[1.7 * inch, 1.0 * inch],
        hAlign="RIGHT",
    )
    totals.setStyle(
        TableStyle(
            [
                ("LINEABOVE", (0, 1), (-1, 1), 1.1, colors.HexColor("#24334a")),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([totals, Spacer(1, 13), Paragraph("TERMS", heading)])
    terms = [
        "Work is planned for a vacant unit with water and electricity available.",
        "We stand behind our workmanship for twelve months following completion.",
        "Hidden water damage, hazardous coatings, and texture reproduction require separate authorization.",
        "Payment schedule: 25% at scheduling and the balance after walkthrough.",
    ]
    for term in terms:
        story.append(Paragraph(f"- {term}", small))
        story.append(Spacer(1, 3))

    def footer(canvas, _document):
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#c7cfda"))
        canvas.line(0.65 * inch, 0.42 * inch, 7.85 * inch, 0.42 * inch)
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#667085"))
        canvas.drawString(0.65 * inch, 0.25 * inch, "Summit Surface Renewal | (951) 555-0142 | bids@summitsurface.example")
        canvas.drawRightString(7.85 * inch, 0.25 * inch, "Page 1 of 1")
        canvas.restoreState()

    document.build(story, onFirstPage=footer)


if __name__ == "__main__":
    build_estimate()
